apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: curlimages/curl:latest
              command: ["/bin/sh", "-c"]
              args:
                - curl -s http://todoapp.mateapp.svc.cluster.local/api/health
              resources:
                requests:
                  cpu: "100m"
                  memory: "100Mi"
                limits:
                  cpu: "200m"
                  memory: "200Mi"
          restartPolicy: OnFailure
