apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: mate-server
  template:
    metadata:
      labels:
        app: mate-server
    spec:
      containers:
        - name: mate-server
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - while true; do
                echo "Calling todoapp service...";
                curl -s http://todoapp.mateapp.svc.cluster.local;
                sleep 5;
              done
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30008
